PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "schema_migrations" ("version" varchar(255) NOT NULL);
INSERT INTO "schema_migrations" VALUES('20130602221734');
INSERT INTO "schema_migrations" VALUES('20130602221829');
INSERT INTO "schema_migrations" VALUES('20130602223518');
INSERT INTO "schema_migrations" VALUES('20130602223639');
INSERT INTO "schema_migrations" VALUES('20130602224011');
INSERT INTO "schema_migrations" VALUES('20130602224210');
INSERT INTO "schema_migrations" VALUES('20130602224515');
INSERT INTO "schema_migrations" VALUES('20130602235307');
INSERT INTO "schema_migrations" VALUES('20130606195700');
CREATE TABLE "questions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar(255), "body" text, "user_id" integer, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "answers" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "body" text, "user_id" integer, "question_id" integer, "best" boolean, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "comments" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "body" text, "question_id" integer, "answer_id" integer, "user_id" integer, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "votes" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "answer_id" integer, "user_id" integer, "positive" boolean, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "labels" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(255), "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "question_labels" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "label_id" integer, "question_id" integer, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(255), "username" varchar(255), "email" varchar(255), "rol" varchar(255) DEFAULT 'regular', "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "encrypted_password" varchar(255) DEFAULT '' NOT NULL, "reset_password_token" varchar(255), "reset_password_sent_at" datetime, "remember_created_at" datetime, "sign_in_count" integer DEFAULT 0, "current_sign_in_at" datetime, "last_sign_in_at" datetime, "current_sign_in_ip" varchar(255), "last_sign_in_ip" varchar(255));
INSERT INTO "users" VALUES(2,'andras','andras','andras@gmail.com','regular','2013-06-06 20:13:47.249671','2013-06-06 20:36:16.765306','$2a$10$DGq0hW6ZamsufJgpVgPNAON5KM3lQxRfp15X/mPoL42aGMMq4rplm',NULL,NULL,NULL,2,'2013-06-06 20:36:16.763202','2013-06-06 20:13:47.439483','127.0.0.1','127.0.0.1');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('users',2);
CREATE UNIQUE INDEX "unique_schema_migrations" ON "schema_migrations" ("version");
CREATE INDEX "index_questions_on_user_id" ON "questions" ("user_id");
CREATE INDEX "index_answers_on_user_id" ON "answers" ("user_id");
CREATE INDEX "index_answers_on_question_id" ON "answers" ("question_id");
CREATE INDEX "index_comments_on_question_id" ON "comments" ("question_id");
CREATE INDEX "index_comments_on_answer_id" ON "comments" ("answer_id");
CREATE INDEX "index_comments_on_user_id" ON "comments" ("user_id");
CREATE INDEX "index_votes_on_answer_id" ON "votes" ("answer_id");
CREATE INDEX "index_votes_on_user_id" ON "votes" ("user_id");
CREATE INDEX "index_question_labels_on_label_id" ON "question_labels" ("label_id");
CREATE INDEX "index_question_labels_on_question_id" ON "question_labels" ("question_id");
CREATE UNIQUE INDEX "index_users_on_email" ON "users" ("email");
CREATE UNIQUE INDEX "index_users_on_reset_password_token" ON "users" ("reset_password_token");
COMMIT;
